#!/usr/bin/env bash

RED='\033[0;31m'
REDI='\033[37;41;3m'
GREEN='\033[32;49m'
BLUE='\033[34;49m'
NC='\033[0m'


echo -e "${RED}
                                                                                        
▗▄▄▖  ▗▄▖  ▗▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖▗▄▖ ▗▖   ▗▖        ▗▄▄▖ ▗▄▄▖▗▄▄▖ ▗▄▄▄▖▗▄▄▖▗▄▄▄▖
▐▌ ▐▌▐▌ ▐▌▐▌     █    █  ▐▛▚▖▐▌▐▌     █ ▐▌ ▐▌▐▌   ▐▌       ▐▌   ▐▌   ▐▌ ▐▌  █  ▐▌ ▐▌ █  
▐▛▀▘ ▐▌ ▐▌ ▝▀▚▖  █    █  ▐▌ ▝▜▌ ▝▀▚▖  █ ▐▛▀▜▌▐▌   ▐▌        ▝▀▚▖▐▌   ▐▛▀▚▖  █  ▐▛▀▘  █  
▐▌   ▝▚▄▞▘▗▄▄▞▘  █  ▗▄█▄▖▐▌  ▐▌▗▄▄▞▘  █ ▐▌ ▐▌▐▙▄▄▖▐▙▄▄▖    ▗▄▄▞▘▝▚▄▄▖▐▌ ▐▌▗▄█▄▖▐▌    █  
                                                                                        
${REDI}github.com/ch1ebak/postinstall-script${NC}
                                                                                        
"


install () {
  echo -e "${GREEN}
                                                                                 
  ▗▄▄▄▖▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖▗▄▖ ▗▖   ▗▖       ▗▄▄▖  ▗▄▖  ▗▄▄▖▗▖ ▗▖ ▗▄▖  ▗▄▄▖▗▄▄▄▖ ▗▄▄▖
    █  ▐▛▚▖▐▌▐▌     █ ▐▌ ▐▌▐▌   ▐▌       ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌▗▞▘▐▌ ▐▌▐▌   ▐▌   ▐▌   
    █  ▐▌ ▝▜▌ ▝▀▚▖  █ ▐▛▀▜▌▐▌   ▐▌       ▐▛▀▘ ▐▛▀▜▌▐▌   ▐▛▚▖ ▐▛▀▜▌▐▌▝▜▌▐▛▀▀▘ ▝▀▚▖
  ▗▄█▄▖▐▌  ▐▌▗▄▄▞▘  █ ▐▌ ▐▌▐▙▄▄▖▐▙▄▄▖    ▐▌   ▐▌ ▐▌▝▚▄▄▖▐▌ ▐▌▐▌ ▐▌▝▚▄▞▘▐▙▄▄▖▗▄▄▞▘
                                                                                 
  ${NC}
  "

  install_core () {
    echo -e "${BLUE}
                                                                    
     ▗▄▄▖ ▗▄▖ ▗▄▄▖ ▗▄▄▄▖    ▗▄▄▖  ▗▄▖  ▗▄▄▖▗▖ ▗▖ ▗▄▖  ▗▄▄▖▗▄▄▄▖ ▗▄▄▖
    ▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌       ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌▗▞▘▐▌ ▐▌▐▌   ▐▌   ▐▌   
    ▐▌   ▐▌ ▐▌▐▛▀▚▖▐▛▀▀▘    ▐▛▀▘ ▐▛▀▜▌▐▌   ▐▛▚▖ ▐▛▀▜▌▐▌▝▜▌▐▛▀▀▘ ▝▀▚▖
    ▝▚▄▄▖▝▚▄▞▘▐▌ ▐▌▐▙▄▄▖    ▐▌   ▐▌ ▐▌▝▚▄▄▖▐▌ ▐▌▐▌ ▐▌▝▚▄▞▘▐▙▄▄▖▗▄▄▞▘
                                                                    
    ${NC}
    "

    CORE="
    brightnessctl
    btop
    calibre
    cantarell-fonts
    capitaine-cursors
    dunst
    easyeffects
    emacs
    fd
    feh
    file-roller
    firefox
    fzf
    github-cli
    gvfs
    gvfs-mtp
    imagemagick
    linux-headers
    lsp-plugins
    mpv
    network-manager-applet
    networkmanager
    nvidia-open-dkms
    nvidia-settings
    nwg-look
    papirus-icon-theme
    pcmanfm
    qbittorrent
    ripgrep
    rofi
    stow
    syncthing
    trash-cli
    ttf-atkinson-hyperlegible
    ttf-jetbrains-mono-nerd
    wget
    yt-dlp
		wezterm
    wget"

		AUR="
    acpilight
    ferdium-bin
    ttf-ancient-fonts
		waves-bin
		zen-browser-bin 
		"
                                                                                                  
    sudo sed -Ei 's/^#(Color)$/\1\nILoveCandy/;s/^#(ParallelDownloads).*/\1 = 5/' /etc/pacman.conf
    sudo pacman -Syu
		echo "System updated."
    sudo pacman -S --needed --noconfirm $CORE
		echo "Core installed."
		sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si
		echo "Paru setup completed."
    paru -S --needed --noconfirm $AUR
    cd /home/$USER/
    trash -v paru
		echo "Paru install completed."
  }

  dotfiles () {
    echo -e "${BLUE}
                                           
    ▗▄▄▄  ▗▄▖▗▄▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖   ▗▄▄▄▖ ▗▄▄▖
    ▐▌  █▐▌ ▐▌ █  ▐▌     █  ▐▌   ▐▌   ▐▌   
    ▐▌  █▐▌ ▐▌ █  ▐▛▀▀▘  █  ▐▌   ▐▛▀▀▘ ▝▀▚▖
    ▐▙▄▄▀▝▚▄▞▘ █  ▐▌   ▗▄█▄▖▐▙▄▄▖▐▙▄▄▖▗▄▄▞▘
                                           
    ${NC}
    "

    paru -S --needed --noconfirm git trash-cli stow
    cd /home/$USER/
    trash .config/qtile .bashrc .Xresources .config/hypr .config/waybar
    git clone https://github.com/ch1ebak/dotfiles
    mv dotfiles .dotfiles
    cd .dotfiles
    stow . --adopt
    cd /home/$USER/
    trash -v /home/$USER/.bash_profile
    chmod +x /home/$USER/.dotfiles/.config/rofi/modules/rofi-power-menu
  }

  sddm () {
    echo -e "${BLUE}
                         
     ▗▄▄▖▗▄▄▄ ▗▄▄▄ ▗▖  ▗▖
    ▐▌   ▐▌  █▐▌  █▐▛▚▞▜▌
     ▝▀▚▖▐▌  █▐▌  █▐▌  ▐▌
    ▗▄▄▞▘▐▙▄▄▀▐▙▄▄▀▐▌  ▐▌
                         
    ${NC}
    "

    paru -S --needed --noconfirm sddm qt6-svg
    systemctl enable sddm
    sudo git clone https://github.com/keyitdev/sddm-astronaut-theme.git /usr/share/sddm/themes/sddm-astronaut-theme
    sudo cp /usr/share/sddm/themes/sddm-astronaut-theme/Fonts/* /usr/share/fonts/
    echo "[Theme]
    Current=sddm-astronaut-theme" | sudo tee /etc/sddm.conf
  }

  install_qtile () {
    echo -e "${BLUE}

    ▗▄▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖   ▗▄▄▄▖
    ▐▌ ▐▌  █    █  ▐▌   ▐▌   
    ▐▌ ▐▌  █    █  ▐▌   ▐▛▀▀▘
    ▐▙▄▟▙▖ █  ▗▄█▄▖▐▙▄▄▖▐▙▄▄▖

    ${NC}
    "

    QTILE_INSTALL="
    picom
    python-pip
    python-psutil
    qtile
    qtile-extras-git
    scrot
    slock
    xclip
    xorg-server
    xorg-xinit
    xorg-xkill
    xorg-xrandr
    "

    paru -S --needed --noconfirm $QTILE_INSTALL
  }

  install_hyprland () {
    echo -e "${BLUE}

    ▗▖ ▗▖▗▖  ▗▖▗▄▄▖ ▗▄▄▖ ▗▖    ▗▄▖ ▗▖  ▗▖▗▄▄▄ 
    ▐▌ ▐▌ ▝▚▞▘ ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌  █
    ▐▛▀▜▌  ▐▌  ▐▛▀▘ ▐▛▀▚▖▐▌   ▐▛▀▜▌▐▌ ▝▜▌▐▌  █
    ▐▌ ▐▌  ▐▌  ▐▌   ▐▌ ▐▌▐▙▄▄▖▐▌ ▐▌▐▌  ▐▌▐▙▄▄▀

    ${NC}
    "

    HYPRLAND_INSTALL="
    cliphist
    egl-wayland
    grim
    hyprcursor
    hypridle
    hyprland
    hyprlock
    hyprpolkitagent
    qt5-wayland
    swaybg
    waybar
    xdg-desktop-portal-hyprland"

    paru -S --needed --noconfirm $HYPRLAND_INSTALL
  }

  install_mango () {
    echo -e "${BLUE}

    ▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖ ▗▄▖ ▗▖ ▗▖ ▗▄▄▖
    ▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌   
    ▐▌  ▐▌▐▛▀▜▌▐▌ ▝▜▌▐▌▝▜▌▐▌ ▐▌▐▌ ▐▌▐▌   
    ▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▝▚▄▞▘▝▚▄▞▘▐▙█▟▌▝▚▄▄▖

    ${NC}
    "

    MANGO_INSTALL="
    cliphist
    egl-wayland
    grim
    mangowm
    swaybg
    hypridle
    hyprlock
    qt5-wayland
    waybar
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    polkit-gnome"

    paru -S --needed --noconfirm $MANGO_INSTALL
  }

  install_gaming () {
    echo -e "${BLUE}

     ▗▄▄▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▖  ▗▖ ▗▄▄▖
    ▐▌   ▐▌ ▐▌▐▛▚▞▜▌  █  ▐▛▚▖▐▌▐▌   
    ▐▌▝▜▌▐▛▀▜▌▐▌  ▐▌  █  ▐▌ ▝▜▌▐▌▝▜▌
    ▝▚▄▞▘▐▌ ▐▌▐▌  ▐▌▗▄█▄▖▐▌  ▐▌▝▚▄▞▘

    ${NC}
    "

    GAMING_APPS="
		dkms
    heroic-games-launcher-bin
    lib32-nvidia-utils
    lib32-vulkan-icd-loader
    nexusmods-app-bin
    nvidia-open-dkms
    nvidia-settings
    nvidia-utils
    proton-ge-custom-bin
    protontricks
    steam
    vulkan-icd-loader
    wine-staging"

    paru -S --needed $GAMING_APPS
  }

  install_vm () {
    echo -e "${BLUE}

    ▗▖  ▗▖▗▄▄▄▖▗▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖▗▄▄▖ 
    ▐▌  ▐▌  █  ▐▌ ▐▌ █  ▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌▐▌   ▐▌   ▐▌ ▐▌
    ▐▌  ▐▌  █  ▐▛▀▚▖ █  ▐▌  ▐▌▐▛▀▜▌▐▌ ▝▜▌▐▌▝▜▌▐▛▀▀▘▐▛▀▚▖
     ▝▚▞▘ ▗▄█▄▖▐▌ ▐▌ █  ▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▝▚▄▞▘▐▙▄▄▖▐▌ ▐▌

    ${NC}
    "

    VIRTMANAGER="
    dmidecode
    dnsmasq
    iptables-nft
    libvirt
    qemu-base
    virt-manager
    "

    paru -S --needed $VIRTMANAGER
    systemctl enable libvirtd
    systemctl start libvirtd
    sudo usermod -aG libvirt $USER

    echo -e "Reboot to apply the changes."
  }

  while true; do
      options=("Install Core" "Clone Dotfiles" "SDDM" "Install Qtile" "Install Hyprland" "Install Mango" "Install Gaming" "Install Virt-Manager" "Back")

      echo -e "Choose an option: "
      select opt in "${options[@]}"; do
          case $REPLY in
              1) install_core; break ;;
              2) dotfiles; break ;;
              3) sddm; break ;;
              4) install_qtile; break ;;
              5) install_hyprland; break ;;
              6) install_mango; break ;;
              7) install_gaming; break ;;
              8) install_vm; break ;;
              9) break 2 ;;
              *) echo "Invalid option $REPLY" >&2
          esac
      done
  done
}


remove () {
  echo -e "${GREEN}
                                                                              
  ▗▄▄▖ ▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖    ▗▄▄▖  ▗▄▖  ▗▄▄▖▗▖ ▗▖ ▗▄▖  ▗▄▄▖▗▄▄▄▖ ▗▄▄▖
  ▐▌ ▐▌▐▌   ▐▛▚▞▜▌▐▌ ▐▌▐▌  ▐▌▐▌       ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌▗▞▘▐▌ ▐▌▐▌   ▐▌   ▐▌   
  ▐▛▀▚▖▐▛▀▀▘▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▐▛▀▀▘    ▐▛▀▘ ▐▛▀▜▌▐▌   ▐▛▚▖ ▐▛▀▜▌▐▌▝▜▌▐▛▀▀▘ ▝▀▚▖
  ▐▌ ▐▌▐▙▄▄▖▐▌  ▐▌▝▚▄▞▘ ▝▚▞▘ ▐▙▄▄▖    ▐▌   ▐▌ ▐▌▝▚▄▄▖▐▌ ▐▌▐▌ ▐▌▝▚▄▞▘▐▙▄▄▖▗▄▄▞▘
                                                                              
  ${NC}
  "

  remove_qtile () {
    echo -e "${BLUE}
                                                                 
    ▗▄▄▖ ▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖    ▗▄▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖   ▗▄▄▄▖
    ▐▌ ▐▌▐▌   ▐▛▚▞▜▌▐▌ ▐▌▐▌  ▐▌▐▌       ▐▌ ▐▌  █    █  ▐▌   ▐▌   
    ▐▛▀▚▖▐▛▀▀▘▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▐▛▀▀▘    ▐▌ ▐▌  █    █  ▐▌   ▐▛▀▀▘
    ▐▌ ▐▌▐▙▄▄▖▐▌  ▐▌▝▚▄▞▘ ▝▚▞▘ ▐▙▄▄▖    ▐▙▄▟▙▖ █  ▗▄█▄▖▐▙▄▄▖▐▙▄▄▖
                                                                 
    ${NC}
    "

    QTILE_REMOVE="
    picom
    python-pip
    qtile
    qtile-extras-git
    scrot
    slock
    xclip
    xorg-xinit
    xorg-xkill
    "

    paru -Rns $QTILE_REMOVE
  }

  remove_hyprland () {
    echo -e "${BLUE}
                                                                                  
    ▗▄▄▖ ▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖    ▗▖ ▗▖▗▖  ▗▖▗▄▄▖ ▗▄▄▖ ▗▖    ▗▄▖ ▗▖  ▗▖▗▄▄▄ 
    ▐▌ ▐▌▐▌   ▐▛▚▞▜▌▐▌ ▐▌▐▌  ▐▌▐▌       ▐▌ ▐▌ ▝▚▞▘ ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌  █
    ▐▛▀▚▖▐▛▀▀▘▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▐▛▀▀▘    ▐▛▀▜▌  ▐▌  ▐▛▀▚▖▐▛▀▘ ▐▌   ▐▛▀▜▌▐▌ ▝▜▌▐▌  █
    ▐▌ ▐▌▐▙▄▄▖▐▌  ▐▌▝▚▄▞▘ ▝▚▞▘ ▐▙▄▄▖    ▐▌ ▐▌  ▐▌  ▐▌ ▐▌▐▌   ▐▙▄▄▖▐▌ ▐▌▐▌  ▐▌▐▙▄▄▀
                                                                                  
    ${NC}
    "

    HYPRLAND_REMOVE="
    cliphist
    grim
    hyprcursor
    hypridle
    hyprland
    hyprlock
    hyprpaper
    hyprpolkitagent
    qt5-wayland
    waybar
    xdg-desktop-portal-hyprland"

    paru -Rns $HYPRLAND_REMOVE
  }

  remove_vm () {
    echo -e "${BLUE}
                                                                                            
    ▗▄▄▖ ▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖    ▗▖  ▗▖▗▄▄▄▖▗▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖▗▄▄▖ 
    ▐▌ ▐▌▐▌   ▐▛▚▞▜▌▐▌ ▐▌▐▌  ▐▌▐▌       ▐▌  ▐▌  █  ▐▌ ▐▌ █  ▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌▐▌   ▐▌   ▐▌ ▐▌
    ▐▛▀▚▖▐▛▀▀▘▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▐▛▀▀▘    ▐▌  ▐▌  █  ▐▛▀▚▖ █  ▐▌  ▐▌▐▛▀▜▌▐▌ ▝▜▌▐▌▝▜▌▐▛▀▀▘▐▛▀▚▖
    ▐▌ ▐▌▐▙▄▄▖▐▌  ▐▌▝▚▄▞▘ ▝▚▞▘ ▐▙▄▄▖     ▝▚▞▘ ▗▄█▄▖▐▌ ▐▌ █  ▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▝▚▄▞▘▐▙▄▄▖▐▌ ▐▌
                                                                                            
    ${NC}
    "

    VIRTMANAGER_REMOVE="
    dmidecode
    dnsmasq
    libvirt
    qemu-base
    virt-manager
    "

    systemctl stop libvirtd
    systemctl disable libvirtd
    paru -S iptables
    paru -Rns $VIRTMANAGER_REMOVE
  }

  while true; do
      options=("Remove Qtile" "Remove Hyprland" "Remove Virt-Manager" "Back")

      echo "Choose and option: "
      select opt in "${options[@]}"; do
          case $REPLY in
              1) remove_qtile; break ;;
              2) remove_hyprland; break ;;
              3) remove_vm; break ;;
              4) break 2 ;;
              *) echo "Invalid option $REPLY" >&2
          esac
      done
  done
}


system () {
  echo -e "${GREEN}
                                                                                                
   ▗▄▄▖▗▖  ▗▖▗▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖    ▗▖  ▗▖ ▗▄▖ ▗▄▄▄▖▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖
  ▐▌    ▝▚▞▘▐▌     █  ▐▌   ▐▛▚▞▜▌    ▐▛▚▞▜▌▐▌ ▐▌  █  ▐▛▚▖▐▌  █  ▐▌   ▐▛▚▖▐▌▐▌ ▐▌▐▛▚▖▐▌▐▌   ▐▌   
   ▝▀▚▖  ▐▌  ▝▀▚▖  █  ▐▛▀▀▘▐▌  ▐▌    ▐▌  ▐▌▐▛▀▜▌  █  ▐▌ ▝▜▌  █  ▐▛▀▀▘▐▌ ▝▜▌▐▛▀▜▌▐▌ ▝▜▌▐▌   ▐▛▀▀▘
  ▗▄▄▞▘  ▐▌ ▗▄▄▞▘  █  ▐▙▄▄▖▐▌  ▐▌    ▐▌  ▐▌▐▌ ▐▌▗▄█▄▖▐▌  ▐▌  █  ▐▙▄▄▖▐▌  ▐▌▐▌ ▐▌▐▌  ▐▌▝▚▄▄▖▐▙▄▄▖
                                                                                                
  ${NC}
  "

  update () {
    echo -e "${BLUE}
                                 
    ▗▖ ▗▖▗▄▄▖ ▗▄▄▄  ▗▄▖▗▄▄▄▖▗▄▄▄▖
    ▐▌ ▐▌▐▌ ▐▌▐▌  █▐▌ ▐▌ █  ▐▌   
    ▐▌ ▐▌▐▛▀▘ ▐▌  █▐▛▀▜▌ █  ▐▛▀▀▘
    ▝▚▄▞▘▐▌   ▐▙▄▄▀▐▌ ▐▌ █  ▐▙▄▄▖
                                 
    ${NC}
    "

    sudo pacman -Syu
    paru -Syu
  }

  cleanup () {
    echo -e "${BLUE}
                                        
     ▗▄▄▖▗▖   ▗▄▄▄▖ ▗▄▖ ▗▖  ▗▖▗▖ ▗▖▗▄▄▖ 
    ▐▌   ▐▌   ▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌ ▐▌▐▌ ▐▌
    ▐▌   ▐▌   ▐▛▀▀▘▐▛▀▜▌▐▌ ▝▜▌▐▌ ▐▌▐▛▀▘ 
    ▝▚▄▄▖▐▙▄▄▖▐▙▄▄▖▐▌ ▐▌▐▌  ▐▌▝▚▄▞▘▐▌   
                                        
    ${NC}
    "

    cleanup_system() {
        printf "%b\n" "Performing system cleanup..."
        paru -Sc --noconfirm
        paru -Rns $(pacman -Qtdq) --noconfirm > /dev/null 2>&1
    }

    common_cleanup() {
        if [ -d /var/tmp ]; then
            find /var/tmp -type f -atime +5 -delete
        fi
        if [ -d /tmp ]; then
            find /tmp -type f -atime +5 -delete
        fi
        if [ -d /var/log ]; then
            find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
        fi
        journalctl --vacuum-time=3d
    }

    clean_data() {
        printf "%b" "Clean up old cache files and empty the trash? (y/N): "
        read -r clean_response
        case $clean_response in
            y|Y)
                printf "%b\n" "Cleaning up old cache files and emptying trash..."
                if [ -d "$HOME/.cache" ]; then
                    find "$HOME/.cache/" -type f -atime +5 -delete
                fi
                if [ -d "$HOME/.local/share/Trash" ]; then
                    find "$HOME/.local/share/Trash" -mindepth 1 -delete
                fi
                printf "%b\n" "Cache and trash cleanup completed."
                ;;
            *)
                printf "%b\n" "Skipping cache and trash cleanup."
                ;;
        esac
    }

    trash-empty
    cleanup_system
    common_cleanup
    clean_data
  }

  while true; do
      options=("Update System" "System Cleanup" "Back")

      echo "Choose an option: "
      select opt in "${options[@]}"; do
          case $REPLY in
              1) update; break ;;
              2) cleanup; break ;;
              3) break 2 ;;
              *) echo "Invalid option $REPLY" >&2
          esac
      done
  done
}


while true; do
    options=("Install Packages" "Remove Packages" "System Maintenance" "Quit")

    echo "Choose an option: "
    select opt in "${options[@]}"; do
        case $REPLY in
            1) install; break ;;
            2) remove; break ;;
            3) system; break ;;
            4) break 2 ;;
            *) echo "Invalid option $REPLY" >&2
        esac
    done
done


echo -e "${RED}
                                                                                              
 ▗▄▖ ▗▖   ▗▖       ▗▄▄▄  ▗▄▖ ▗▖  ▗▖▗▄▄▄▖
▐▌ ▐▌▐▌   ▐▌       ▐▌  █▐▌ ▐▌▐▛▚▖▐▌▐▌   
▐▛▀▜▌▐▌   ▐▌       ▐▌  █▐▌ ▐▌▐▌ ▝▜▌▐▛▀▀▘
▐▌ ▐▌▐▙▄▄▖▐▙▄▄▖    ▐▙▄▄▀▝▚▄▞▘▐▌  ▐▌▐▙▄▄▖
                                                                                              
${REDI}Don't forget to reboot!${NC}
                                                                                              
"
